version: '3'
services:
  cassandra:
    image: cassandra:4.1.3
    container_name: db-cassandra
    ports:
      - '9042:9042'
    volumes:
      - "./scripts/make-cassandra-tables.sh:/make-cassandra-tables.sh"
    command: "sh /make-cassandra-tables.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
  grafana:
    image: grafana/grafana:10.2.0
    container_name: viz-grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=hadesarchitect-cassandra-datasource
  pyspark:
    build: 
      context: .
      dockerfile: PySparkDockerFile
    volumes:
      - "./scripts/real_time_processing.py:/real_time_processing.py"
      - "./scripts/pyspark_init.sh:/pyspark_init.sh"
      - "./input:/input"
    command: '/pyspark_init.sh'
    container_name: py-spark
  python:
    build:
      context: .
      dockerfile: PythonDockerFile
    container_name: finnhub-python
    volumes:
      - "./input:/input"
      - "./scripts/get_trades_from_finnhub.py:/get_trades_from_finnhub.py"
    command: "python /get_trades_from_finnhub.py"
    environment:
      - FINNHUB_TOKEN=${FINNHUB_TOKEN}